//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OpenALEax.rc
//
#define IDD_OPENALEAX_DIALOG            102
#define IDS_PROPSHT_CAPTION             103
#define IDI_NVIDIA                      104
#define IDR_MAINFRAME                   128
#define IDD_EAXLIST                     202
#define IDD_EAXBUF                      203
#define IDC_PLAY                        1000
#define IDC_STOP                        1001
#define IDC_EAXLIST_ENVIRONMENT_SIZE    1002
#define IDC_EAXLIST_ENVIRONMENT_DIFFUSION 1003
#define IDC_EAXLIST_ROOM                1004
#define IDC_EAXLIST_ENVIRONMENT_PRESET  1005
#define IDC_EAXLIST_ROOMHF              1006
#define IDC_EAXLIST_ENVIRONMENT_SIZE_VALUE 1007
#define IDC_EAXLIST_ENVIRONMENT_DIFFUSION_VALUE 1008
#define IDC_EAXLIST_ROOM_VALUE          1009
#define IDC_EAXLIST_ROOMHF_VALUE        1010
#define IDC_EAXLIST_ROOMROLLOFF         1011
#define IDC_EAXLIST_ROOMROLLOFF_VALUE   1012
#define IDC_EAXLIST_AIRABSORPTION       1013
#define IDC_EAXLIST_AIRABSORPTION_VALUE 1014
#define IDC_EAXLIST_REFLECTIONS         1015
#define IDC_EAXLIST_REFLECTIONS_VALUE   1016
#define IDC_EAXLIST_REFLECTIONSDELAY    1017
#define IDC_EAXLIST_REFLECTIONSDELAY_VALUE 1018
#define IDC_EAXLIST_SCALE_REFLECTIONS   1019
#define IDC_EAXLIST_SCALE_REFLECTIONSDELAY 1020
#define IDC_TAB1                        1020
#define IDC_EAXBUF_DIRECT               1021
#define IDC_EAXLIST_REVERB              1021
#define IDC_EAXBUF_DIRECT_VALUE         1022
#define IDC_EAXLIST_REVERB_VALUE        1022
#define IDC_EAXLBUF_DIRECTHF            1023
#define IDC_EAXLIST_REVERBDELAY         1023
#define IDC_EAXBUF_DIRECTHF_VALUE       1024
#define IDC_EAXLIST_REVERBDELAY_VALUE   1024
#define IDC_EAXBUF_ROOM                 1025
#define IDC_EAXLIST_SCALE_REVERB        1025
#define IDC_EAXBUFF_AUTO_DIRECTHF       1026
#define IDC_EAXLIST_SCALE_REVERBDELAY   1026
#define IDC_EAXBUF_ROOM_VALUE           1027
#define IDC_EAXLIST_DECAYTIME           1027
#define IDC_EAXBUF_AUTO_ROOM            1028
#define IDC_EAXLIST_DECAYTIME_VALUE     1028
#define IDC_EAXBUF_ROOMHF               1029
#define IDC_EAXLIST_DECAYHF             1029
#define IDC_EAXBUF_ROOMHF_VALUE         1030
#define IDC_EAXLIST_DECAYHF_VALUE       1030
#define IDC_EAXBUF_SCALE_ROOMHF         1031
#define IDC_EAXLIST_SCALE_DECAYTIME     1031
#define IDC_EAXBUF_AUTO_ROOMHF          1031
#define IDC_EAXBUF_ROOMROLLOFF          1032
#define IDC_EAXLIST_SCALE_DECAYCLIP     1032
#define IDC_EAXLIST_CLIP_DECAY          1032
#define IDC_EAXBUF_ROOMROLLOFF_VALUE    1033
#define IDC_EAXBUF_AIRABSORPTION        1034
#define IDC_EAXBUF_AIRABSORPTION_VALUE  1035
#define IDC_EAXLBUF_OUTSIDEHF           1036
#define IDC_EAXBUF_OUTSIDEHF_VALUE      1037
#define IDC_EAXBUF_OBSTRUCTION          1038
#define IDC_EAXBUF_OBSTRUCTION_VALUE    1039
#define IDC_EAXLBUF_OBSTRUCTIONLF       1040
#define IDC_EAXBUF_OBSTRUCTIONLF_VALUE  1041
#define IDC_EAXBUF_OCCLUSION            1043
#define IDC_EAXBUF_OCCLUSION_VALUE      1044
#define IDC_EAXLBUF_OCCLUSIONLF         1045
#define IDC_EAXBUF_OCCLUSIONLF_VALUE    1046
#define IDC_EAXLBUF_OCCLUSIONROOM       1047
#define IDC_EAXBUF_OCCLUSIONROOM_VALUE  1048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
